name = "lala"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
usage_model = "unbound"
main = "index.ts"

[durable_objects]
bindings = [{ name = "LALA", class_name = "Lala" }]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Lala"]
