name = "lala"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
usage_model = "unbound"
main = "index.ts"
account_id = "b03830d9ae163ab8ac4a868e4ddd0e84"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Lala"]
